# Dependencies
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Eisen Blog'
tagline:          'Blog On Jekyll'
description:      ''
url:              https://aisensiy.github.io
baseurl:          ''

author:
  name:           'Eisen Xu'
  url:            https://github.com/aisensiy

paginate:         5

gems: [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aisensiy
