name: aisensiy-blog
static_sites:
- build_command: bundle exec jekyll build -d ./public
  environment_slug: jekyll
  github:
    branch: main
    deploy_on_push: true
    repo: aiseensiy/aisensiy.github.com
  name: aisensiy-blog